[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
